export const defaultAppSettings: AppSettings = {
  autoStart: false,
  closeWindowOption: "hide",
  fontFamily: "system-ui",
  borderRadius: 10,
  downloadPath: "",
  primaryColor: "#1ed760",
  backgroundColor: "",
  audioQuality: "auto",
  hiddenMenuKeys: [],
  displayMode: "card",
  ffmpegPath: "",
  themeMode: "system",
  pageTransition: "none",
  showSearchHistory: true,
  proxySettings: {
    type: "none",
    host: "",
    port: undefined,
    username: "",
    password: "",
  },
  sideMenuCollapsed: false,
  sideMenuWidth: 200,
  sideMenuCollectionFolded: {
    created: false,
    collected: false,
  },
  localMusicDirs: [],
  showLyrics: true,
  lyricsColor: "#ffffff",
  showSpectrum: false,
  spectrumColor: "#595959",
  showCover: true,
  showBlurredBackground: true,
  fullScreenBackgroundColor: "",
  searchMusicOnly: true,
};
